'use client';

import { Check, Copy, Gift, Users } from 'lucide-react';
import { useState } from 'react';

export function FriendsTab() {
  const [copied, setCopied] = useState(false);
  const inviteLink = 't.me/agenb_miner_bot?start=invite_8J4K2';
  async function copyLink() { await navigator.clipboard?.writeText(`https://${inviteLink}`); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  return <section className="tab-content"><div className="page-heading"><span className="eyebrow">REFERRAL HUB</span><h1>Grow together</h1><p>Bring your crew in. Everyone earns more when the network grows.</p></div><div className="invite-card"><div className="invite-mark"><Users size={22} /></div><div><span className="muted-label">YOUR INVITE LINK</span><strong>{inviteLink}</strong></div><button className="icon-button copy-button" onClick={copyLink} aria-label="Copy invite link">{copied ? <Check size={18} /> : <Copy size={18} />}</button></div><div className="stats-grid referral-stats"><div className="stat-card"><span className="stat-icon"><Users size={16} /></span><span className="muted-label">Total referrals</span><strong>24</strong></div><div className="stat-card"><span className="stat-icon"><Gift size={16} /></span><span className="muted-label">Referral rewards</span><strong>2,400 AGENB</strong></div><div className="stat-card"><span className="stat-icon"><span className="tiny-agenb">A</span></span><span className="muted-label">Team earnings</span><strong>8,642 AGENB</strong></div></div><div className="section-heading"><div><span className="eyebrow">YOUR NETWORK</span><h2>Team hierarchy</h2></div></div><div className="network-tree"><div className="tree-person root-person"><span>Y</span><div><strong>You</strong><small>Level 0 · 12.4k AGENB</small></div></div><div className="tree-branch"><div className="tree-person"><span>AM</span><div><strong>Alex M.</strong><small>8 referrals · +840 AGENB</small></div></div><div className="tree-person"><span>SK</span><div><strong>Sofia K.</strong><small>5 referrals · +520 AGENB</small></div></div><div className="tree-person faded"><span>+19</span><div><strong>More miners</strong><small>Growing your network</small></div></div></div></div></section>;
}
