'use client';

import { Check, Lock, TrendingUp, Zap } from 'lucide-react';
type MinersTabProps = { onWatch: () => void; canWatch: boolean };
const miners = Array.from({ length: 12 }, (_, index) => ({ level: index + 1, price: [0, 25, 75, 180, 400, 850, 1600, 2900, 5100, 8800, 14400, 22000][index], hash: (0.2 + index * 0.24).toFixed(2) }));

export function MinersTab({ onWatch, canWatch }: MinersTabProps) {
  return <section className="tab-content"><div className="page-heading"><span className="eyebrow">HARDWARE STORE</span><h1>Scale your mine</h1><p>Upgrade your rig to increase your passive output.</p></div><div className="chart-card"><div className="chart-top"><div><span className="muted-label">PNL GROWTH</span><strong>+28.6%</strong></div><span className="chart-period">LAST 30 DAYS</span></div><svg className="growth-chart" viewBox="0 0 600 170" preserveAspectRatio="none" aria-label="PNL growth chart"><path className="chart-fill" d="M0 150 C60 142, 75 120, 130 128 S190 80, 240 105 S300 68, 345 80 S400 42, 450 62 S520 18, 600 24 L600 170 L0 170Z" /><path className="chart-line" d="M0 150 C60 142, 75 120, 130 128 S190 80, 240 105 S300 68, 345 80 S400 42, 450 62 S520 18, 600 24" /></svg><div className="chart-axis"><span>01 MAY</span><span>15 MAY</span><span>30 MAY</span></div></div><div className="section-heading"><div><span className="eyebrow">12 MODELS</span><h2>Hardware upgrades</h2></div><TrendingUp size={20} /></div><div className="miner-grid">{miners.map((miner) => { const active = miner.level === 1; return <div className={`miner-card ${active ? 'active' : ''}`} key={miner.level}><div className="miner-title"><span>LVL {miner.level}</span>{active ? <span className="status-pill"><Check size={12} /> ACTIVE</span> : <Lock size={16} />}</div><strong>{active ? 'Starter rig' : `Miner ${String(miner.level).padStart(2, '0')}`}</strong><div className="hash-rate"><Zap size={14} /> {miner.hash} TH/s</div>{active ? <small>Currently mining</small> : <><small>NEED {miner.level * 100} ATF</small><button className="upgrade-button">${miner.price.toLocaleString()} <span>UPGRADE</span></button></>}</div>; })}</div><button className="boost-panel compact" onClick={onWatch} disabled={!canWatch}><div className="boost-icon"><Zap size={18} /></div><div><strong>Power boost</strong><span>Watch an ad to mine faster</span></div><span className="arrow-mark">→</span></button></section>;
}
